### ISSUE TITLE
Decide what FFs to share

### ISSUE THREAD

**Issue by punkpony** [Erastova-group/ClayCode#44]
Decide what FF to share + annotate the files, incl refs:
- [x] ClayFF with extra Fe(II)
- [x] 'Amber' ions by Pengfei Li, these come in HFE, IOD and CN. I think IOD is best for us, but can include 3 sets. Need to rename them from 'Amber' cause they are not technically 'Amber'

**Comment by hp115** [comment]
Now in Ions.ff
